modules: trusted-firmware-a: Disable AArch32 context for ARMv9-A
ARMv9-A is AArch64-only and does not support AArch32 execution states
at EL1/EL2/EL3. Configure TF-A build to disable AArch32 register
context (CTX_INCLUDE_AARCH32_REGS=0) when building for ARMv9-A platforms.

This fixes TF-A boot failures on ARMv9-A non-secure variants where
TF-A would panic with:
  ERROR: EL1 supports AArch64-only. Please set build flag
         CTX_INCLUDE_AARCH32_REGS = 0

(cherry picked from commit a479606c338360922e6cebfbefed0a30215b8682)

Original-Signed-off-by: Nicolas Pitre <npitre@baylibre.com>
GitOrigin-RevId: a479606c338360922e6cebfbefed0a30215b8682
Cr-Build-Id: 8697820917959855649
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8697820917959855649
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I33cba9ce156d98900a312114105ac0a997c3ae62
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7171045
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>