drivers: dma: Remove unused function
Building with clang warns:

drivers/dma/dma_emul.c:73:20: error: unused function
'dma_emul_xfer_is_error_status' [-Werror,-Wunused-function]
static inline bool dma_emul_xfer_is_error_status(int status)
                   ^

(cherry picked from commit 538b525ef15a5689372cbdffbac86e35df8460e1)

Original-Signed-off-by: Tom Hughes <tomhughes@chromium.org>
GitOrigin-RevId: 538b525ef15a5689372cbdffbac86e35df8460e1
Cr-Build-Id: 8723052172249940737
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8723052172249940737
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I0bfe6a2cbe544f17df8223710726f24b222c8d29
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6261363
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>