xtensa: fix error: use of undeclared identifier 'intenable2'
This is likely a miss from:
df40dff6fb1 arch: xtensa: clean up interrupt handling

(cherry picked from commit 926efb8fc1a8f013da92d6c74dbdc87fc2654702)

Original-Signed-off-by: William Tambe <williamt@cadence.com>
GitOrigin-RevId: 926efb8fc1a8f013da92d6c74dbdc87fc2654702
Cr-Build-Id: 8698908081405170945
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698908081405170945
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I5bdd5e54520c5e09ffe457ae519136dc8cd106fe
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7129495
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>