drivers: sensor: fix possible unaligned access icm45686
icm45686_encoded_fifo_payload is defined as packed struct,
while the nested structures are not. It causes an issue of
potential unaligned access to accel and gyro members.
The issue was detected by clang compiling with
-Wunaligned-access flag:

```
icm45686.h:52:6: error: field accel within 'struct icm45686.h:46:3)'
is less aligned than 'struct icm45686.h:48:4)' and is usually due
to 'struct icm45686.h:46:3)' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]

icm45686.h:57:6: error: field gyro within 'struct icm45686.h:46:3)'
is less aligned than 'struct icm45686.h:53:4)' and is usually due
to 'struct icm45686.h:46:3)' being packed,
which can lead to unaligned accesses [-Werror,-Wunaligned-access]
```

Small C code snippet to demonstrate the reported issue:
```
struct icm45686_encoded_fifo_payload icm45686;
// prints 1:
printf("%lu\n", __alignof__(icm45686));
// prints 1:
printf("%lu\n", __alignof__(icm45686.accel));
// prints 2:
printf("%lu\n", __alignof__(typeof(icm45686.accel)));
```

This commit resolves the following Zephyr issue:
by adding `packed` attribute to accel and gyro members.

(cherry picked from commit 0436b8abd8310cb20abbaf0f2fb3432b3ee71f72)

Original-https: //github.com/zephyrproject-rtos/zephyr/issues/101142
Original-Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
GitOrigin-RevId: 0436b8abd8310cb20abbaf0f2fb3432b3ee71f72
Cr-Build-Id: 8693834649729444993
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8693834649729444993
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I8c318dc7907b0595872a01d3f8155e267909101e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7376012
Commit-Queue: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>