Revert "drivers: gpio_cc13xx_cc26xx: Update for latest sdk"
This reverts commit 99e7223a1ce73e7b52f614e0feda0b52a884c804.

Breaks CI with the following compilation error in SPI.c:52:

Failing tests (cc3220sf_launchxl/cc3220sf)
- sample.net.sockets.echo.offload.simplelink
- sample.net.sockets.http_get.offload.simplelink
- sample.net.wifi

(cherry picked from commit 06e86e95da1c168f1578bb2c20da37a8c078fec0)

Original-error: 'SPI_MASTER' undeclared here (not in a function)
Original-Signed-off-by: Benjamin Cabé <benjamin@zephyrproject.org>
GitOrigin-RevId: 06e86e95da1c168f1578bb2c20da37a8c078fec0
Cr-Build-Id: 8720130420530112897
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8720130420530112897
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I616ba714a244715c790f300389b9e71e3af36fc6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6362575
Tested-by: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Bot-Commit: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>
Commit-Queue: ChromeOS Prod (Robot) <chromeos-ci-prod@chromeos-bot.iam.gserviceaccount.com>