drivers: i2c: stm32: fix compilation with DMA
- implicit declaration of function 'stm32_buf_in_nocache'
- undefined reference to 'stm32_buf_in_nocache'

(cherry picked from commit 6e018bbf04eccad1c67229a247f4f1ddb123c494)

Original-fixes:
Original-Signed-off-by: Mickael Bosch <mickael.bosch@linux.com>
GitOrigin-RevId: 6e018bbf04eccad1c67229a247f4f1ddb123c494
Cr-Build-Id: 8703913562775995409
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8703913562775995409
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I16e1e0a5cf89eec260af3a029ae61cc5b7e91812
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6944946
Tested-by: Al Semjonovs <asemjonovs@google.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Reviewed-by: Jeremy Bettis <jbettis@chromium.org>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>