doc: external_content: exclude backup files
For most people, this should be only an optimization.

For Emacs TRAMP (ssh) users, this fixes the following build failure when
a file is not saved yet. This build failure happens because TRAMP
creates backup files on the local host and seems to use deliberately
broken symlinks as "bookmarks" to those local files.

file snippets/.#index.rst

 snippets/.#index.rst: broken symbolic link
                       to userid@hostname.intel.com.966265369654

```
Traceback
=========

 Traceback (most recent call last):
   File "/usr/lib/python3.13/site-packages/sphinx/events.py", in emit
     results.append(listener.handler(self.app, *args))
                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
   File " doc/_extensions/zephyr/external_content.py", in sync_contents
     shutil.copy(src, dst)
     ~~~~~~~~~~~^^^^^^^^^^
   File "/usr/lib/python3.13/shutil.py", line 428, in copy
     copyfile(src, dst, follow_symlinks=follow_symlinks)
     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.13/shutil.py", line 260, in copyfile
     with open(src, 'rb') as fsrc:
          ~~~~^^^^^^^^^^^
 FileNotFoundError: [Errno 2] No such file or directory:
                      '___/zephyr/snippets/.#index.rst'
```

Just for the record, these backup files were already discussed in commit
bab7df9f9e4 (".gitignore: do not ignore .\#* files")

(cherry picked from commit d6f28bd3d40e25653d4ff2f5329b5dc9ed6328d7)

Original-Signed-off-by: Marc Herbert <marc.herbert@intel.com>
GitOrigin-RevId: d6f28bd3d40e25653d4ff2f5329b5dc9ed6328d7
Cr-Build-Id: 8704230653470391569
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8704230653470391569
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I26a7b6fc74739aa50d1730404c722b591a30abfc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/6928555
Tested-by: Al Semjonovs <asemjonovs@google.com>
Reviewed-by: Al Semjonovs <asemjonovs@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>