Bluetooth: Classic: AVRCP: Fix another Clang/LLVM build failure
subsys/bluetooth/host/classic/shell/avrcp.c:407:3: error: label followed
by a declaration is a C23 extension [-Werror,-Wc23-extensions]
  407 |                 uint64_t identifier;
      |                 ^

(cherry picked from commit 3ab1caa87f073893fb564d1bd8062eaa8f8523d5)

Original-Signed-off-by: Johan Hedberg <johan.hedberg@silabs.com>
GitOrigin-RevId: 3ab1caa87f073893fb564d1bd8062eaa8f8523d5
Cr-Build-Id: 8698221080423948257
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698221080423948257
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: I8b4ff695e2c95d11d900c8af5e9bca9a3e2d9e9c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7158231
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>