drivers: gnss: f9p: fix multiple rtk enabled instances
The U-blox F9P driver uses the GNSS_RTK_DATA_CALLBACK_DEFINE macro to
register a callback for when RTK data is available. This is an issue when
multiple instances of the F9P are available and RTK is enabled since this
macro leads to a naming collision. The following compilation error is

     error: redefinition of '_gnss_rtk_data_callback__f9p_rtk_data_cb'

This is because GNSS_RTK_DATA_CALLBACK_DEFINE only uses `_callback` to
identify the callback being registered. As a fix, use the recently
introduced GNSS_DT_RTK_DATA_CALLBACK_DEFINE instead, which takes into
account the `_node_id` while naming the callback.

(cherry picked from commit c0ba4d3ffefa00bf206c5f6db44ea7972dbcf988)

Original-reported:
Original-Signed-off-by: Pedro André <pedro@sentrytechnologies.ai>
GitOrigin-RevId: c0ba4d3ffefa00bf206c5f6db44ea7972dbcf988
Cr-Build-Id: 8698228605132682497
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8698228605132682497
Copybot-Job-Name: zephyr-main-copybot-downstream
Change-Id: Ib997318a65200e92ee5682be231753bd757c8058
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/zephyr/+/7157542
Reviewed-by: Fabio Baltieri <fabiobaltieri@google.com>
Tested-by: ChromeOS Copybot <copybot@chops-service-accounts.iam.gserviceaccount.com>
Commit-Queue: Fabio Baltieri <fabiobaltieri@google.com>